import Head from "next/head";
import Sidebar from "../components/Sidebar";
import styled from "styled-components";

export default function Home() {

  return (
    <div>
      <Head>
        <title>Home | Whatsapp Clone</title>
        <meta name="description" content="Generated by AK The Dev" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultContainer>
        <Sidebar />
        <DefaultHome className="mdHidden">
          <div className="card mdHidden">

            <div className="card__side" id="front">
              <h3
                style={{
                  margin: "2rem 15rem -13px 15rem",
                  fontSize: "2.5rem",
                }}
              >
                Dive chat clone
              </h3>

              <p
                style={{
                  margin: "5rem 3rem 2rem -3rem",
                  letterSpacing: "0px",
                  fontSize: "1.6rem",
                  color: "#212529",
                  textAlign: "center",

                }}
              >
                click on chat to start messaging
              </p>
            </div>
          </div>
        </DefaultHome>
      </DefaultContainer>
    </div>
  );
}

const DefaultContainer = styled.div`
  display: flex;
`;

const DefaultHome = styled.div`
  display: flex;
  flex: 1;
  height: 100vh;
  justify-content: center;
  align-items: center;
`;

// const InfoBox = styled.div`
//   height: 60rem;
//   width: 56rem;
//   background-color: #99d98c;
//   font-weight: 500;
//   font-size: 1.4rem;
//   border-radius: 1rem;
//   box-shadow: 0 20px 30px 0 rgba(0, 0, 0, 0.19);
// `;
